"""add org_settings and agent_policies

Revision ID: 657480f24bee
Revises: 771b814a374a
Create Date: 2026-02-04 17:51:41.656772

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '657480f24bee'
down_revision: Union[str, None] = '771b814a374a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_policies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('org_id', sa.Integer(), nullable=False),
    sa.Column('allow_replies', sa.Boolean(), nullable=False),
    sa.Column('allow_reactions', sa.Boolean(), nullable=False),
    sa.Column('allow_critique', sa.Boolean(), nullable=False),
    sa.Column('max_risk_score', sa.Integer(), nullable=False),
    sa.Column('require_human_review', sa.Boolean(), nullable=False),
    sa.Column('banned_topics', sa.String(length=500), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['orgs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('org_id', name='uq_agent_policies_org_id')
    )
    op.create_index(op.f('ix_agent_policies_org_id'), 'agent_policies', ['org_id'], unique=False)
    op.create_table('org_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('org_id', sa.Integer(), nullable=False),
    sa.Column('agents_enabled', sa.Boolean(), nullable=False),
    sa.Column('auto_publish', sa.Boolean(), nullable=False),
    sa.Column('max_agents_per_post', sa.Integer(), nullable=False),
    sa.Column('max_actions_per_day', sa.Integer(), nullable=False),
    sa.Column('spawn_probability_base', sa.Float(), nullable=False),
    sa.Column('locale', sa.String(length=10), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['orgs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('org_id', name='uq_org_settings_org_id')
    )
    op.create_index(op.f('ix_org_settings_org_id'), 'org_settings', ['org_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_org_settings_org_id'), table_name='org_settings')
    op.drop_table('org_settings')
    op.drop_index(op.f('ix_agent_policies_org_id'), table_name='agent_policies')
    op.drop_table('agent_policies')
    # ### end Alembic commands ###
