"""add agent_profiles and agent_actions

Revision ID: 75f067f42c1f
Revises: 657480f24bee
Create Date: 2026-02-04 19:59:13.015162

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '75f067f42c1f'
down_revision: Union[str, None] = '657480f24bee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('org_id', sa.Integer(), nullable=False),
    sa.Column('display_name', sa.String(length=120), nullable=False),
    sa.Column('handle', sa.String(length=60), nullable=False),
    sa.Column('avatar_url', sa.String(length=500), nullable=False),
    sa.Column('persona_seed', sa.Text(), nullable=False),
    sa.Column('topics', sa.String(length=500), nullable=False),
    sa.Column('style', sa.String(length=200), nullable=False),
    sa.Column('risk_level', sa.Integer(), nullable=False),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['orgs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('org_id', 'handle', name='uq_agent_profiles_org_handle')
    )
    op.create_index(op.f('ix_agent_profiles_org_id'), 'agent_profiles', ['org_id'], unique=False)
    op.create_table('agent_actions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('org_id', sa.Integer(), nullable=False),
    sa.Column('agent_id', sa.Integer(), nullable=False),
    sa.Column('target_type', sa.String(length=20), nullable=False),
    sa.Column('target_id', sa.Integer(), nullable=False),
    sa.Column('action_type', sa.String(length=30), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('policy_score', sa.Integer(), nullable=False),
    sa.Column('policy_reason', sa.String(length=500), nullable=False),
    sa.Column('llm_provider', sa.String(length=50), nullable=False),
    sa.Column('llm_model', sa.String(length=80), nullable=False),
    sa.Column('prompt_hash', sa.String(length=80), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['agent_id'], ['agent_profiles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['org_id'], ['orgs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_actions_agent_id'), 'agent_actions', ['agent_id'], unique=False)
    op.create_index(op.f('ix_agent_actions_org_id'), 'agent_actions', ['org_id'], unique=False)
    op.create_index('ix_agent_actions_org_status_created', 'agent_actions', ['org_id', 'status', 'created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_agent_actions_org_status_created', table_name='agent_actions')
    op.drop_index(op.f('ix_agent_actions_org_id'), table_name='agent_actions')
    op.drop_index(op.f('ix_agent_actions_agent_id'), table_name='agent_actions')
    op.drop_table('agent_actions')
    op.drop_index(op.f('ix_agent_profiles_org_id'), table_name='agent_profiles')
    op.drop_table('agent_profiles')
    # ### end Alembic commands ###
