"""add posts tags post_tags comments

Revision ID: 762e3003a4f4
Revises: 75f067f42c1f
Create Date: 2026-02-04 20:06:51.206892

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '762e3003a4f4'
down_revision: Union[str, None] = '75f067f42c1f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('posts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('org_id', sa.Integer(), nullable=False),
    sa.Column('author_user_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('slug', sa.String(length=120), nullable=False),
    sa.Column('body_md', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['author_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['org_id'], ['orgs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_posts_author_user_id'), 'posts', ['author_user_id'], unique=False)
    op.create_index(op.f('ix_posts_org_id'), 'posts', ['org_id'], unique=False)
    op.create_index('ix_posts_org_status_created', 'posts', ['org_id', 'status', 'created_at'], unique=False)
    op.create_index(op.f('ix_posts_slug'), 'posts', ['slug'], unique=False)
    op.create_table('tags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('org_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=60), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['orgs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('org_id', 'name', name='uq_tags_org_name')
    )
    op.create_index(op.f('ix_tags_org_id'), 'tags', ['org_id'], unique=False)
    op.create_table('comments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('org_id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('parent_comment_id', sa.Integer(), nullable=True),
    sa.Column('author_type', sa.String(length=10), nullable=False),
    sa.Column('author_user_id', sa.Integer(), nullable=True),
    sa.Column('author_agent_id', sa.Integer(), nullable=True),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['author_agent_id'], ['agent_profiles.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['author_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['org_id'], ['orgs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parent_comment_id'], ['comments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_comments_author_agent_id'), 'comments', ['author_agent_id'], unique=False)
    op.create_index(op.f('ix_comments_author_user_id'), 'comments', ['author_user_id'], unique=False)
    op.create_index(op.f('ix_comments_org_id'), 'comments', ['org_id'], unique=False)
    op.create_index('ix_comments_org_post_created', 'comments', ['org_id', 'post_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_comments_parent_comment_id'), 'comments', ['parent_comment_id'], unique=False)
    op.create_index(op.f('ix_comments_post_id'), 'comments', ['post_id'], unique=False)
    op.create_table('post_tags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('post_id', 'tag_id', name='uq_post_tag')
    )
    op.create_index(op.f('ix_post_tags_post_id'), 'post_tags', ['post_id'], unique=False)
    op.create_index(op.f('ix_post_tags_tag_id'), 'post_tags', ['tag_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_post_tags_tag_id'), table_name='post_tags')
    op.drop_index(op.f('ix_post_tags_post_id'), table_name='post_tags')
    op.drop_table('post_tags')
    op.drop_index(op.f('ix_comments_post_id'), table_name='comments')
    op.drop_index(op.f('ix_comments_parent_comment_id'), table_name='comments')
    op.drop_index('ix_comments_org_post_created', table_name='comments')
    op.drop_index(op.f('ix_comments_org_id'), table_name='comments')
    op.drop_index(op.f('ix_comments_author_user_id'), table_name='comments')
    op.drop_index(op.f('ix_comments_author_agent_id'), table_name='comments')
    op.drop_table('comments')
    op.drop_index(op.f('ix_tags_org_id'), table_name='tags')
    op.drop_table('tags')
    op.drop_index(op.f('ix_posts_slug'), table_name='posts')
    op.drop_index('ix_posts_org_status_created', table_name='posts')
    op.drop_index(op.f('ix_posts_org_id'), table_name='posts')
    op.drop_index(op.f('ix_posts_author_user_id'), table_name='posts')
    op.drop_table('posts')
    # ### end Alembic commands ###
