"""create orgs users org_members

Revision ID: 771b814a374a
Revises: aaf8eeb1494e
Create Date: 2026-02-04 17:24:02.080338

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '771b814a374a'
down_revision: Union[str, None] = 'aaf8eeb1494e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
