"""add org_usage_daily

Revision ID: d9fbf3ad2165
Revises: 762e3003a4f4
Create Date: 2026-02-04 20:57:06.911282

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd9fbf3ad2165'
down_revision: Union[str, None] = '762e3003a4f4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('org_usage_daily',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('org_id', sa.Integer(), nullable=False),
    sa.Column('day_utc', sa.Date(), nullable=False),
    sa.Column('actions_spawned', sa.Integer(), nullable=False),
    sa.Column('actions_published', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['orgs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('org_id', 'day_utc', name='uq_org_usage_day')
    )
    op.create_index(op.f('ix_org_usage_daily_day_utc'), 'org_usage_daily', ['day_utc'], unique=False)
    op.create_index(op.f('ix_org_usage_daily_org_id'), 'org_usage_daily', ['org_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_org_usage_daily_org_id'), table_name='org_usage_daily')
    op.drop_index(op.f('ix_org_usage_daily_day_utc'), table_name='org_usage_daily')
    op.drop_table('org_usage_daily')
    # ### end Alembic commands ###
