""" 
Auto-generated SQLAlchemy model for Order.

This file was generated by Forge using the lego_backend/model_sqlalchemy.py.j2 template.
"""

from sqlalchemy import Column, Integer, DateTime
from sqlalchemy.sql import func
from core.database.database import Base
from sqlalchemy import String, Text, Numeric, Boolean


class Order(Base):
    __tablename__ = "orders"

    id = Column(Integer, primary_key=True, index=True)
    reference = Column(String(50), nullable=False, index=True)
    total_amount = Column(Numeric(10, 2), nullable=False)

    created_at = Column(
        DateTime(timezone=True),
        server_default=func.now(),
        nullable=False,
    )
    updated_at = Column(
        DateTime(timezone=True),
        onupdate=func.now(),
        nullable=True,
    )