version: '3.8'

services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_DB: forge_saas_prod
      POSTGRES_USER: forge
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U forge -d forge_saas_prod"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    build: ./backend
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgresql://forge:${DATABASE_PASSWORD}@postgres:5432/forge_saas_prod
      SECRET_KEY: ${SECRET_KEY}
      DEBUG: "false"
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped

  ui:
    build: ./ui
    ports:
      - "8501:8501"
    environment:
      BACKEND_URL: http://backend:8000
      BACKEND_PUBLIC_URL: ${BACKEND_PUBLIC_URL}
    depends_on:
      - backend
    restart: unless-stopped

volumes:
  postgres_data: