""" 
Auto-generated SQLAlchemy model for Product.

This file was generated by Forge using the lego_backend/model_sqlalchemy.py.j2 template.
"""

from sqlalchemy import Column, Integer, DateTime
from sqlalchemy.sql import func
from core.database.database import Base
from sqlalchemy import String, Text, Numeric, Boolean


class Product(Base):
    __tablename__ = "products"

    id = Column(Integer, primary_key=True, index=True)
    name = Column(String(255), nullable=False, index=True)
    description = Column(Text, nullable=True)
    price = Column(Numeric(10, 2), nullable=False)
    is_active = Column(Boolean, nullable=False, server_default='1')

    created_at = Column(
        DateTime(timezone=True),
        server_default=func.now(),
        nullable=False,
    )
    updated_at = Column(
        DateTime(timezone=True),
        onupdate=func.now(),
        nullable=True,
    )