"""init

Revision ID: a3683ddb987c
Revises: 1f53bda92b4b
Create Date: 2025-09-25 16:22:38.742474
"""

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'a3683ddb987c'
down_revision = '1f53bda92b4b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
