"""Fix artifact model

Revision ID: ba37eabeee95
Revises: bd142ee8c0ea
Create Date: 2025-10-01 23:03:59.288891

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ba37eabeee95'
down_revision: Union[str, Sequence[str], None] = 'bd142ee8c0ea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('artifacts', sa.Column('artifact_type', sa.String(), nullable=True))
    op.add_column('artifacts', sa.Column('content', sa.Text(), nullable=True))
    op.alter_column('artifacts', 'kind',
               existing_type=sa.VARCHAR(length=30),
               nullable=True)
    op.alter_column('artifacts', 'path',
               existing_type=sa.VARCHAR(length=512),
               nullable=True)
    op.drop_constraint(op.f('artifacts_project_id_fkey'), 'artifacts', type_='foreignkey')
    op.drop_column('artifacts', 'sha256')
    op.drop_column('artifacts', 'size')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('artifacts', sa.Column('size', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('artifacts', sa.Column('sha256', sa.VARCHAR(length=64), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('artifacts_project_id_fkey'), 'artifacts', 'projects', ['project_id'], ['id'])
    op.alter_column('artifacts', 'path',
               existing_type=sa.VARCHAR(length=512),
               nullable=False)
    op.alter_column('artifacts', 'kind',
               existing_type=sa.VARCHAR(length=30),
               nullable=False)
    op.drop_column('artifacts', 'content')
    op.drop_column('artifacts', 'artifact_type')
    # ### end Alembic commands ###
