"""init

Revision ID: 1f53bda92b4b
Revises: 1bb4a971bc3c
Create Date: 2025-09-25 16:22:19.249664
"""

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '1f53bda92b4b'
down_revision = '1bb4a971bc3c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
