"""Add size and sha256 columns to artifacts

Revision ID: a5d3661ccee5
Revises: ba37eabeee95
Create Date: 2025-10-01 23:06:18.220507

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a5d3661ccee5'
down_revision: Union[str, Sequence[str], None] = 'ba37eabeee95'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('artifacts', sa.Column('size', sa.Integer(), nullable=True))
    op.add_column('artifacts', sa.Column('sha256', sa.String(length=64), nullable=True))
    op.alter_column('artifacts', 'kind',
               existing_type=sa.VARCHAR(length=30),
               nullable=False)
    op.alter_column('artifacts', 'path',
               existing_type=sa.VARCHAR(length=512),
               nullable=False)
    op.create_foreign_key(None, 'artifacts', 'projects', ['project_id'], ['id'])
    op.drop_column('artifacts', 'content')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('artifacts', sa.Column('content', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'artifacts', type_='foreignkey')
    op.alter_column('artifacts', 'path',
               existing_type=sa.VARCHAR(length=512),
               nullable=True)
    op.alter_column('artifacts', 'kind',
               existing_type=sa.VARCHAR(length=30),
               nullable=True)
    op.drop_column('artifacts', 'sha256')
    op.drop_column('artifacts', 'size')
    # ### end Alembic commands ###
