from __future__ import annotations

from pathlib import Path
import shutil


ROOT = Path(__file__).parent
FROM_REQ = ROOT / "workdir" / "from_requirements"
PROJECT_SLUG = "demo_ecommerce"
PROJECT_ROOT = ROOT / "generated_projects" / PROJECT_SLUG / "backend"


def _pick_first_dir(parent: Path, leaf: str) -> Path | None:
    """
    Busca el primer directorio que termine en 'leaf' bajo 'parent'.
    Ej.: leaf='products' -> .../business_ecommerce_product_catalog/products
    """
    matches = list(parent.glob(f"**/{leaf}"))
    return matches[0] if matches else None


def _copy_resource(src_dir: Path, resource: str) -> None:
    """
    Copia models_/schemas_/services_/routers_ para un recurso dado
    (product, order, etc.) a la estructura canonical del backend.
    """
    mapping = [
        (f"models_{resource}.py",   PROJECT_ROOT / "models" / f"{resource}.py"),
        (f"schemas_{resource}.py",  PROJECT_ROOT / "schemas" / f"{resource}.py"),
        (f"services_{resource}.py", PROJECT_ROOT / "services" / f"{resource}.py"),
        (f"routers_{resource}.py",  PROJECT_ROOT / "routers" / f"{resource}.py"),
    ]

    for src_name, dest in mapping:
        src = src_dir / src_name
        if not src.exists():
            print(f"[forge_lego_pack_project] WARNING: no existe {src}")
            continue
        dest.parent.mkdir(parents=True, exist_ok=True)
        shutil.copy2(src, dest)
        print(f"[forge_lego_pack_project] Copiado {src} -> {dest}")


def main() -> None:
    print(f"[forge_lego_pack_project] ROOT: {ROOT}")
    print(f"[forge_lego_pack_project] FROM_REQ: {FROM_REQ}")

    if not FROM_REQ.exists():
        print("[forge_lego_pack_project] ERROR: no existe workdir/from_requirements. "
              "Primero genera recursos con /api/forge/generate_from_requirements.")
        return

    # 1) Localizar dirs de products y orders generados desde requisitos.
    products_dir = _pick_first_dir(FROM_REQ, "products")
    orders_dir = _pick_first_dir(FROM_REQ, "orders")

    print(f"[forge_lego_pack_project] products_dir: {products_dir}")
    print(f"[forge_lego_pack_project] orders_dir:   {orders_dir}")

    if products_dir is None and orders_dir is None:
        print("[forge_lego_pack_project] No encontré ni products ni orders. "
              "¿Has llamado ya al endpoint /api/forge/generate_from_requirements?")
        return

    # 2) Copiar recursos de Product -> backend/models|schemas|services|routers
    if products_dir is not None:
        _copy_resource(products_dir, "product")

    # 3) Copiar recursos de Order -> backend/models|schemas|services|routers
    if orders_dir is not None:
        _copy_resource(orders_dir, "order")

    # 4) Crear README del proyecto generado.
    PROJECT_ROOT.mkdir(parents=True, exist_ok=True)
    readme = PROJECT_ROOT.parent / "README.md"
    if not readme.exists():
        readme.write_text(
            f"# Generated Project: {PROJECT_SLUG}\n\n"
            "This backend was assembled from Lego resources generated by Forge.\n\n"
            "Structure:\n"
            "  - backend/models/*.py\n"
            "  - backend/schemas/*.py\n"
            "  - backend/services/*.py\n"
            "  - backend/routers/*.py\n\n"
            "You can now wire these into a full FastAPI app or package them into a ZIP.\n",
            encoding="utf-8",
        )
        print(f"[forge_lego_pack_project] Creado README: {readme}")
    else:
        print(f"[forge_lego_pack_project] README ya existía: {readme}")

    print("[forge_lego_pack_project] Proyecto empaquetado en:",
          PROJECT_ROOT.parent)


if __name__ == "__main__":
    main()
