import { SupportedCountry } from '../supabase'

export interface ContractTerms {
  country: SupportedCountry
  language: string
  law: string
  jurisdiction: string
  payment_protection: string
  cancellation_policy: string
  dispute_resolution: string
  warranty_days: number
  platform_fee_pct: number
  // Nuevos tipos contractuales
  platform_role: string           // Solva como intermediario, no empleador
  independent_contractor: string  // Pro es autónomo, no empleado
  escrow_conditions: string       // Condiciones explícitas del escrow
  data_processing: string         // RGPD/LOPD — tratamiento de datos
  home_access_confidentiality: string  // Acceso al domicilio
  b2b_clause: string | null       // Solo cuando cliente es empresa
  liability_limit: string         // Límite de responsabilidad de Solva
}

export const CONTRACT_TEMPLATES: Record<SupportedCountry, ContractTerms> = {
  ES: {
    country: 'ES',
    language: 'es-ES',
    law: 'Ley Orgánica 3/2018 (LOPD) y legislación civil española',
    jurisdiction: 'España',
    payment_protection: 'El pago queda retenido en escrow hasta confirmación de entrega',
    cancellation_policy: 'Cancelación gratuita hasta 24h antes del inicio del servicio',
    dispute_resolution: 'Mediación a través de Solva. En caso de no resolución: arbitraje según normativa española',
    warranty_days: 7,
    platform_fee_pct: 10,
    platform_role: 'Solva actúa exclusivamente como plataforma intermediaria. No es parte del contrato de servicios, no es empleadora del profesional ni prestadora del servicio. La relación contractual existe únicamente entre cliente y profesional.',
    independent_contractor: 'El profesional actúa como trabajador autónomo independiente. No existe relación laboral, de dependencia ni de exclusividad con Solva. El profesional fija sus propias tarifas, horarios y condiciones de trabajo.',
    escrow_conditions: 'El importe acordado queda retenido por Solva hasta que el cliente confirme la correcta ejecución del servicio o transcurran 72 horas desde la fecha de finalización sin reclamación. En caso de disputa, el importe queda bloqueado hasta resolución. Solva no paga intereses sobre fondos retenidos.',
    data_processing: 'Los datos personales de ambas partes son tratados por Solva como responsable del tratamiento conforme a la LOPD-GDD y el RGPD. Los datos mínimos necesarios son compartidos entre las partes para la ejecución del contrato. Solva no vende datos a terceros.',
    home_access_confidentiality: 'El profesional se compromete a mantener estricta confidencialidad sobre el domicilio, sus habitantes, bienes y cualquier información obtenida durante la prestación del servicio. Queda prohibido fotografiar, grabar o divulgar información del inmueble.',
    b2b_clause: 'Cuando el cliente actúa en calidad de empresario o profesional, no son aplicables los derechos de desistimiento ni las protecciones específicas de consumidores previstas en el TRLGDCU.',
    liability_limit: 'La responsabilidad de Solva como intermediaria queda limitada al importe de la comisión cobrada por la transacción. Solva no responde por daños causados por el profesional en el domicilio del cliente, para lo cual el profesional debe contar con seguro de responsabilidad civil.',
  },
  FR: {
    country: 'FR',
    language: 'fr-FR',
    law: 'Code Civil français, Code de la consommation et RGPD',
    jurisdiction: 'France',
    payment_protection: 'Le paiement est conservé en séquestre jusqu\'à confirmation de livraison',
    cancellation_policy: 'Annulation gratuite jusqu\'à 24h avant le début du service',
    dispute_resolution: 'Médiation via Solva. En cas de non-résolution: arbitrage selon droit français',
    warranty_days: 7,
    platform_fee_pct: 10,
    platform_role: 'Solva agit exclusivement en tant que plateforme intermédiaire au sens de l\'article L111-7 du Code de la consommation. Solva n\'est pas partie au contrat de service et n\'est pas l\'employeur du professionnel.',
    independent_contractor: 'Le professionnel intervient en qualité de travailleur indépendant (auto-entrepreneur, micro-entreprise ou société). Aucun lien de subordination n\'existe avec Solva. Le professionnel fixe librement ses tarifs et conditions d\'intervention.',
    escrow_conditions: 'Les fonds sont déposés sur un compte séquestre géré par Solva. La libération intervient à la confirmation du client ou 72h après la fin de la prestation sans réclamation. En cas de litige, les fonds restent bloqués jusqu\'à résolution. Aucun intérêt n\'est versé sur les fonds séquestrés.',
    data_processing: 'Solva traite les données personnelles en qualité de responsable de traitement conformément au RGPD (règlement UE 2016/679) et à la loi Informatique et Libertés. Les données nécessaires à l\'exécution du contrat sont partagées entre les parties.',
    home_access_confidentiality: 'Le professionnel s\'engage à maintenir une stricte confidentialité concernant le domicile, ses occupants et tout bien ou information dont il aurait connaissance dans le cadre de la prestation. Toute captation d\'image ou divulgation est interdite.',
    b2b_clause: 'Lorsque le client agit en qualité de professionnel, les dispositions protectrices du droit de la consommation (droit de rétractation, information précontractuelle renforcée) ne sont pas applicables.',
    liability_limit: 'La responsabilité de Solva en tant qu\'intermédiaire est limitée au montant de la commission perçue. Solva ne saurait être tenue responsable des dommages causés par le professionnel lors de l\'exécution de la prestation.',
  },
  BE: {
    country: 'BE',
    language: 'fr-BE',
    law: 'Code civil belge, Code de droit économique (CDE), Règlement général sur la protection des données (RGPD)',
    jurisdiction: 'Belgique',
    payment_protection: 'Le paiement est conservé en séquestre jusqu\'à confirmation de livraison',
    cancellation_policy: 'Annulation gratuite jusqu\'à 24h avant le début du service',
    dispute_resolution: 'Médiation via Solva. En cas de non-résolution: Service de Médiation pour le Consommateur (SMC) ou arbitrage selon droit belge',
    warranty_days: 7,
    platform_fee_pct: 10,
    platform_role: 'Solva est une plateforme d\'intermédiation au sens du Règlement (UE) 2019/1150 sur les relations plateformes-entreprises. Solva n\'est pas partie au contrat de service, n\'est pas l\'employeur du prestataire et n\'est pas responsable de l\'exécution de la prestation. Solva est enregistrée conformément au CDE.',
    independent_contractor: 'Le prestataire intervient en qualité de travailleur indépendant conformément au statut social des indépendants belge (loi du 27 juillet 1967). Aucune relation de travail au sens de la loi du 3 juillet 1978 relative aux contrats de travail n\'existe avec Solva. Le prestataire est responsable de ses cotisations INASTI et de sa couverture en assurance RC professionnelle.',
    escrow_conditions: 'Les fonds sont conservés sur un compte de tiers séparé conformément aux bonnes pratiques financières belges. La libération intervient à la confirmation du client ou 72h après la fin sans réclamation. En cas de contestation, les fonds demeurent bloqués jusqu\'à résolution amiable ou décision du SMC. Solva ne verse aucun intérêt sur les fonds séquestrés. Solva n\'est pas un établissement de paiement agréé — pour les montants élevés, le paiement peut transiter par un PSP agréé par la BNB.',
    data_processing: 'Solva traite les données à caractère personnel en qualité de responsable de traitement conformément au RGPD et à la loi belge du 30 juillet 2018. Les données sont conservées au sein de l\'EEE. Les parties disposent d\'un droit d\'accès, de rectification et d\'effacement auprès de dpo@getsolva.co. En cas de litige relatif au traitement des données: Autorité de Protection des Données (APD) — www.autoriteprotectiondonnees.be.',
    home_access_confidentiality: 'Le prestataire s\'engage à respecter la vie privée des occupants conformément à l\'article 22 de la Constitution belge et à la loi du 30 juillet 2018. Il est interdit de photographier, filmer, enregistrer ou divulguer toute information relative au domicile, à ses occupants ou à leurs biens. Toute violation constitue une infraction pénale en droit belge.',
    b2b_clause: 'Lorsque le client est une entreprise au sens du CDE (art. I.1), les dispositions protectrices du consommateur du Livre VI CDE ne sont pas applicables. Les parties conviennent que la loi belge du 4 avril 2019 sur les pratiques commerciales entre entreprises s\'applique subsidiairement.',
    liability_limit: 'La responsabilité de Solva en qualité d\'intermédiaire est strictement limitée au montant de la commission perçue sur la transaction concernée. Solva décline toute responsabilité pour les dommages matériels, corporels ou immatériels causés par le prestataire lors de l\'exécution de sa mission. Le prestataire est tenu de souscrire une assurance RC professionnelle adéquate.',
  },
  NL: {
    country: 'NL',
    language: 'nl-NL',
    law: 'Burgerlijk Wetboek, Wet handhaving consumentenbescherming en AVG/GDPR',
    jurisdiction: 'Nederland',
    payment_protection: 'Betaling wordt in escrow gehouden tot bevestiging van levering',
    cancellation_policy: 'Gratis annulering tot 24 uur voor aanvang van de dienst',
    dispute_resolution: 'Bemiddeling via Solva. Bij geen oplossing: Geschillencommissie of arbitrage volgens Nederlands recht',
    warranty_days: 7,
    platform_fee_pct: 10,
    platform_role: 'Solva treedt uitsluitend op als bemiddelingsplatform. Solva is geen partij bij de serviceovereenkomst en is niet de werkgever van de dienstverlener.',
    independent_contractor: 'De dienstverlener werkt als zelfstandige (ZZP-er of BV). Er bestaat geen arbeidsrelatie met Solva. De dienstverlener is verantwoordelijk voor eigen belastingaangiften en beroepsaansprakelijkheidsverzekering.',
    escrow_conditions: 'Betalingen worden op een derdenrekening bewaard. Vrijgave vindt plaats na bevestiging door de opdrachtgever of 72 uur na voltooiing zonder klacht. Bij een geschil blijft het bedrag geblokkeerd totdat dit is opgelost.',
    data_processing: 'Solva verwerkt persoonsgegevens als verwerkingsverantwoordelijke overeenkomstig de AVG (verordening EU 2016/679) en de UAVG. Betrokkenen kunnen hun rechten uitoefenen via privacy@getsolva.co.',
    home_access_confidentiality: 'De dienstverlener verplicht zich tot strikte geheimhouding over het woonadres, de bewoners en alle informatie die tijdens de dienstverlening is verkregen. Fotograferen, filmen of openbaarmaking is verboden.',
    b2b_clause: 'Wanneer de opdrachtgever handelt als ondernemer, zijn de consumentenbeschermingsbepalingen van Boek 6 BW niet van toepassing.',
    liability_limit: 'De aansprakelijkheid van Solva als bemiddelaar is beperkt tot het bedrag van de ontvangen commissie. Solva is niet aansprakelijk voor schade veroorzaakt door de dienstverlener.',
  },
  DE: {
    country: 'DE',
    language: 'de-DE',
    law: 'Bürgerliches Gesetzbuch (BGB), Telemediengesetz (TMG) und DSGVO',
    jurisdiction: 'Deutschland',
    payment_protection: 'Zahlung wird im Treuhandkonto bis zur Lieferungsbestätigung gehalten',
    cancellation_policy: 'Kostenlose Stornierung bis 24h vor Dienstleistungsbeginn',
    dispute_resolution: 'Mediation über Solva. Bei Nichtlösung: Schiedsverfahren nach deutschem Recht',
    warranty_days: 7,
    platform_fee_pct: 10,
    platform_role: 'Solva ist ausschließlich als Vermittlungsplattform tätig. Solva ist nicht Vertragspartei des Dienstleistungsvertrages und nicht Arbeitgeber des Dienstleisters.',
    independent_contractor: 'Der Dienstleister ist selbstständiger Unternehmer (Gewerbetreibender oder Freiberufler). Es besteht kein Arbeitsverhältnis mit Solva. Der Dienstleister ist verantwortlich für Steuern und Betriebshaftpflichtversicherung.',
    escrow_conditions: 'Zahlungen werden auf einem Treuhandkonto verwahrt. Die Freigabe erfolgt nach Bestätigung durch den Auftraggeber oder 72 Stunden nach Leistungserbringung ohne Beanstandung.',
    data_processing: 'Solva verarbeitet personenbezogene Daten als Verantwortlicher gemäß DSGVO und BDSG. Betroffene können ihre Rechte unter datenschutz@getsolva.co geltend machen.',
    home_access_confidentiality: 'Der Dienstleister verpflichtet sich zur Verschwiegenheit über die Wohnung, ihre Bewohner und alle im Rahmen der Dienstleistung erlangten Informationen gemäß §§ 203 ff. StGB.',
    b2b_clause: 'Handelt der Auftraggeber als Unternehmer im Sinne des § 14 BGB, finden die Verbraucherschutzvorschriften (§§ 312 ff. BGB) keine Anwendung.',
    liability_limit: 'Die Haftung von Solva als Vermittler ist auf die erhaltene Provision beschränkt. Solva haftet nicht für Schäden, die der Dienstleister verursacht.',
  },
  PT: {
    country: 'PT',
    language: 'pt-PT',
    law: 'Código Civil português, Lei de Defesa do Consumidor e RGPD',
    jurisdiction: 'Portugal',
    payment_protection: 'O pagamento fica retido em escrow até confirmação de entrega',
    cancellation_policy: 'Cancelamento gratuito até 24h antes do início do serviço',
    dispute_resolution: 'Mediação via Solva. Em caso de não resolução: CNIACC ou arbitragem segundo direito português',
    warranty_days: 7,
    platform_fee_pct: 10,
    platform_role: 'A Solva atua exclusivamente como plataforma intermediária. Não é parte do contrato de serviços nem empregadora do prestador.',
    independent_contractor: 'O prestador atua como trabalhador independente. Não existe relação de trabalho subordinado com a Solva.',
    escrow_conditions: 'Os fundos ficam retidos em conta caucionada até confirmação do cliente ou 72h após conclusão sem reclamação.',
    data_processing: 'A Solva trata dados pessoais como responsável pelo tratamento ao abrigo do RGPD e da Lei n.º 58/2019. Os titulares podem exercer os seus direitos em privacidade@getsolva.co.',
    home_access_confidentiality: 'O prestador compromete-se a manter sigilo sobre o domicílio, os seus habitantes e todas as informações obtidas durante a prestação do serviço.',
    b2b_clause: 'Quando o cliente atua na qualidade de profissional, não se aplicam as disposições protetoras dos consumidores previstas na Lei de Defesa do Consumidor.',
    liability_limit: 'A responsabilidade da Solva como intermediária limita-se ao valor da comissão cobrada na transação.',
  },
  IT: {
    country: 'IT',
    language: 'it-IT',
    law: 'Codice Civile italiano, Codice del Consumo (D.Lgs. 206/2005) e GDPR',
    jurisdiction: 'Italia',
    payment_protection: 'Il pagamento è trattenuto in escrow fino alla conferma di consegna',
    cancellation_policy: 'Cancellazione gratuita fino a 24 ore prima dell\'inizio del servizio',
    dispute_resolution: 'Mediazione tramite Solva. In caso di mancata risoluzione: arbitrato secondo diritto italiano',
    warranty_days: 7,
    platform_fee_pct: 10,
    platform_role: 'Solva agisce esclusivamente come piattaforma intermediaria. Non è parte del contratto di servizi né datore di lavoro del prestatore.',
    independent_contractor: 'Il prestatore opera come lavoratore autonomo. Non esiste alcun rapporto di lavoro subordinato con Solva.',
    escrow_conditions: 'I fondi sono trattenuti in conto vincolato fino alla conferma del cliente o 72 ore dopo il completamento senza reclami.',
    data_processing: 'Solva tratta i dati personali come titolare del trattamento ai sensi del GDPR e del D.Lgs. 196/2003. Gli interessati possono esercitare i propri diritti scrivendo a privacy@getsolva.co.',
    home_access_confidentiality: 'Il prestatore si impegna a mantenere la riservatezza sull\'abitazione, sui suoi occupanti e su tutte le informazioni acquisite durante la prestazione del servizio.',
    b2b_clause: 'Quando il cliente agisce in qualità di professionista, non si applicano le disposizioni del Codice del Consumo relative ai contratti con i consumatori.',
    liability_limit: 'La responsabilità di Solva come intermediario è limitata all\'importo della commissione percepita sulla transazione.',
  },
  GB: {
    country: 'GB',
    language: 'en-GB',
    law: 'UK Contract Law, Consumer Rights Act 2015 and UK GDPR',
    jurisdiction: 'United Kingdom',
    payment_protection: 'Payment is held in escrow until delivery confirmation',
    cancellation_policy: 'Free cancellation up to 24h before service start',
    dispute_resolution: 'Mediation via Solva. If unresolved: arbitration under UK law or Ombudsman Services',
    warranty_days: 7,
    platform_fee_pct: 10,
    platform_role: 'Solva acts solely as an intermediary platform under the Digital Markets, Competition and Consumers Act 2024. Solva is not a party to the service contract and is not the employer of the service provider.',
    independent_contractor: 'The service provider operates as a self-employed individual or company. No employment relationship exists with Solva under the Employment Rights Act 1996.',
    escrow_conditions: 'Funds are held in a client account until confirmed by the customer or 72 hours after completion without dispute. In case of dispute, funds remain held until resolution.',
    data_processing: 'Solva processes personal data as a data controller under UK GDPR and the Data Protection Act 2018. Data subjects may exercise their rights at privacy@getsolva.co. Supervisory authority: Information Commissioner\'s Office (ICO).',
    home_access_confidentiality: 'The service provider undertakes to maintain strict confidentiality regarding the property, its occupants and any information obtained during service delivery, in accordance with the common law duty of confidentiality.',
    b2b_clause: 'Where the customer is acting in the course of a business, the consumer protection provisions of the Consumer Rights Act 2015 do not apply.',
    liability_limit: 'Solva\'s liability as an intermediary is limited to the commission received on the relevant transaction. Solva is not liable for damage caused by the service provider.',
  },
  MX: {
    country: 'MX',
    language: 'es-MX',
    law: 'Código Civil Federal, Ley Federal de Protección al Consumidor (LFPC) y Ley Federal de Protección de Datos Personales',
    jurisdiction: 'México',
    payment_protection: 'El pago queda retenido en escrow hasta confirmación de entrega',
    cancellation_policy: 'Cancelación gratuita hasta 24h antes del inicio del servicio',
    dispute_resolution: 'Mediación a través de Solva. En caso de no resolución: PROFECO o arbitraje civil',
    warranty_days: 5,
    platform_fee_pct: 10,
    platform_role: 'Solva actúa como plataforma intermediaria. No es parte del contrato de servicios ni empleadora del profesional en términos de la Ley Federal del Trabajo.',
    independent_contractor: 'El profesional actúa como trabajador independiente. No existe relación laboral con Solva conforme a la LFT. El profesional es responsable de sus obligaciones fiscales ante el SAT.',
    escrow_conditions: 'El importe queda retenido hasta confirmación del cliente o 72 horas tras la finalización sin reclamación. En disputa, queda bloqueado hasta resolución.',
    data_processing: 'Solva trata datos personales conforme a la LFPDPPP y su Reglamento. El aviso de privacidad está disponible en getsolva.co/privacidad. Los titulares pueden ejercer derechos ARCO en privacidad@getsolva.co.',
    home_access_confidentiality: 'El profesional se obliga a guardar confidencialidad sobre el domicilio y sus ocupantes conforme al Código Penal Federal en materia de revelación de secretos.',
    b2b_clause: 'Cuando el cliente actúa como persona moral o empresario, no son aplicables las protecciones específicas de la LFPC para consumidores.',
    liability_limit: 'La responsabilidad de Solva como intermediaria se limita al monto de la comisión cobrada. Solva no responde por daños causados por el profesional.',
  },
  CO: {
    country: 'CO',
    language: 'es-CO',
    law: 'Código Civil colombiano, Estatuto del Consumidor (Ley 1480/2011) y Ley 1581 de 2012',
    jurisdiction: 'Colombia',
    payment_protection: 'El pago queda retenido en escrow hasta confirmación de entrega',
    cancellation_policy: 'Cancelación gratuita hasta 24h antes del inicio del servicio',
    dispute_resolution: 'Mediación a través de Solva. En caso de no resolución: SIC o arbitraje civil',
    warranty_days: 5,
    platform_fee_pct: 10,
    platform_role: 'Solva actúa como plataforma intermediaria digital. No es empleadora del profesional ni prestadora directa del servicio.',
    independent_contractor: 'El profesional actúa como trabajador independiente. No existe vínculo laboral con Solva conforme al Código Sustantivo del Trabajo.',
    escrow_conditions: 'El importe queda retenido hasta confirmación del cliente o 72 horas tras la finalización sin reclamación.',
    data_processing: 'Solva trata datos personales conforme a la Ley 1581 de 2012 y el Decreto 1377 de 2013. Los titulares pueden ejercer sus derechos en privacidad@getsolva.co.',
    home_access_confidentiality: 'El profesional se compromete a guardar reserva sobre el domicilio y sus ocupantes conforme al Código Penal colombiano.',
    b2b_clause: 'Cuando el cliente actúa como persona jurídica o empresario, no aplican las protecciones específicas del Estatuto del Consumidor para personas naturales.',
    liability_limit: 'La responsabilidad de Solva como intermediaria se limita al valor de la comisión cobrada.',
  },
  AR: {
    country: 'AR',
    language: 'es-AR',
    law: 'Código Civil y Comercial argentino, Ley de Defensa del Consumidor (24.240) y Ley 25.326',
    jurisdiction: 'Argentina',
    payment_protection: 'El pago queda retenido en escrow hasta confirmación de entrega',
    cancellation_policy: 'Cancelación gratuita hasta 24h antes del inicio del servicio',
    dispute_resolution: 'Mediación a través de Solva. En caso de no resolución: arbitraje según normativa argentina',
    warranty_days: 5,
    platform_fee_pct: 10,
    platform_role: 'Solva actúa como plataforma intermediaria. No es empleadora del profesional ni prestadora del servicio.',
    independent_contractor: 'El profesional actúa como trabajador autónomo. No existe relación de dependencia con Solva conforme a la LCT.',
    escrow_conditions: 'El importe queda retenido hasta confirmación del cliente o 72 horas tras la finalización sin reclamación.',
    data_processing: 'Solva trata datos personales conforme a la Ley 25.326 de Protección de Datos Personales. Los titulares pueden ejercer sus derechos en privacidad@getsolva.co.',
    home_access_confidentiality: 'El profesional se compromete a guardar confidencialidad sobre el domicilio y sus ocupantes conforme al Código Penal argentino.',
    b2b_clause: 'Cuando el cliente actúa como empresa, no aplican las protecciones específicas de la Ley 24.240 para consumidores finales.',
    liability_limit: 'La responsabilidad de Solva como intermediaria se limita al monto de la comisión cobrada.',
  },
  BR: {
    country: 'BR',
    language: 'pt-BR',
    law: 'Código Civil brasileiro, Código de Defesa do Consumidor (CDC) e LGPD (Lei 13.709/2018)',
    jurisdiction: 'Brasil',
    payment_protection: 'O pagamento fica retido em escrow até confirmação de entrega',
    cancellation_policy: 'Cancelamento gratuito até 24h antes do início do serviço',
    dispute_resolution: 'Mediação via Solva. Em caso de não resolução: PROCON ou arbitragem conforme lei brasileira',
    warranty_days: 7,
    platform_fee_pct: 10,
    platform_role: 'A Solva atua exclusivamente como plataforma intermediária. Não é parte do contrato de serviços nem empregadora do prestador nos termos da CLT.',
    independent_contractor: 'O prestador atua como trabalhador autônomo ou MEI. Não existe relação de emprego com a Solva.',
    escrow_conditions: 'Os fundos ficam retidos até confirmação do cliente ou 72h após conclusão sem reclamação.',
    data_processing: 'A Solva trata dados pessoais como controladora nos termos da LGPD. Os titulares podem exercer os seus direitos em privacidade@getsolva.co. Autoridade supervisora: ANPD.',
    home_access_confidentiality: 'O prestador compromete-se a manter sigilo sobre o domicílio, os seus moradores e todas as informações obtidas durante a prestação do serviço.',
    b2b_clause: 'Quando o contratante é pessoa jurídica, não se aplicam as disposições protetoras do CDC destinadas ao consumidor final.',
    liability_limit: 'A responsabilidade da Solva como intermediária limita-se ao valor da comissão recebida na transação.',
  },
  CL: {
    country: 'CL',
    language: 'es-CL',
    law: 'Código Civil chileno, Ley del Consumidor (19.496) y Ley 19.628',
    jurisdiction: 'Chile',
    payment_protection: 'El pago queda retenido en escrow hasta confirmación de entrega',
    cancellation_policy: 'Cancelación gratuita hasta 24h antes del inicio del servicio',
    dispute_resolution: 'Mediación a través de Solva. En caso de no resolución: SERNAC o arbitraje según normativa chilena',
    warranty_days: 5,
    platform_fee_pct: 10,
    platform_role: 'Solva actúa como plataforma intermediaria. No es empleadora del profesional ni prestadora directa del servicio.',
    independent_contractor: 'El profesional actúa como trabajador independiente. No existe relación laboral con Solva conforme al Código del Trabajo.',
    escrow_conditions: 'El importe queda retenido hasta confirmación del cliente o 72 horas tras la finalización sin reclamación.',
    data_processing: 'Solva trata datos personales conforme a la Ley 19.628 y la nueva Ley 21.719. Los titulares pueden ejercer sus derechos en privacidad@getsolva.co.',
    home_access_confidentiality: 'El profesional se compromete a guardar confidencialidad sobre el domicilio y sus ocupantes conforme a la legislación penal chilena.',
    b2b_clause: 'Cuando el cliente actúa como empresa, no aplican las protecciones específicas de la Ley del Consumidor.',
    liability_limit: 'La responsabilidad de Solva como intermediaria se limita al monto de la comisión cobrada.',
  },
}

export function getContractTerms(country: SupportedCountry): ContractTerms {
  return CONTRACT_TEMPLATES[country] ?? CONTRACT_TEMPLATES['ES']
}
